---
title: "Lab 6"
output: pdf_document
---
Turn in one copy for each group, both PDF/Word and R Markdown files.

## Lab Overview


The entire lab will be worth 20 points. 

## Questions
Answer the following questions in this R Markdown document. Please include code where necessary.

### 1. Capital BikeShare Data
This data set contains single bike trips from March of 2017 for the Capital BikeShare system in Washington, D.C.

### a. (3 points)
Download the file [http://math.montana.edu/ahoegh/teaching/stat408/datasets/biketrips2017.csv](http://math.montana.edu/ahoegh/teaching/stat408/datasets/biketrips2017.csv) and summarize the data set. What does each column represent? What about each row? 

### b. (5 points)
Compute how many trips were made for each of the 31 days in the month of March. I have filtered out cases that started and ended on different days. Note this will require an intermediate step to extract the day of the month.

### c. (3 points)
Create a new variable that contains the trip time.

### d. (3 points)
What percentage of bike rentals last more than an hour?

### e. (6 points)

Create a figure to plot the trip time as a function of day of week (Sunday, Monday, etc...). Make sure to include an informative title and sort the weekday into chronological ordering.


